# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### 4.1. Import NumPy as np

In [2]:
import numpy as np
# Or import numpy
# the "as" keyword is used for aliasing or renaming imported libraries and modules

#### 4.2. Create an array of 10 zeros

In [ ]:
array_zeros = np.zeros(10)
print(f"Array of 10 zeros: {array_zeros} ")

# create a 2D array (matrix) of size 5x2, filled with zeros

array_zeros1 = np.zeros((5, 2))
print(f"A 2D array filled with zeros: \n {array_zeros1} ")

Array of 10 zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
A 2D array filled with zeros: 
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]] 


#### 4.3. Create an array of 10 ones

In [ ]:
array_ones = np.ones(10)
print(f"Array of 10 ones: {array_ones} ")

# create a 2D array of size 2x5 filled with ones.

array_ones1 = np.ones((5, 2))
print(f"A 2D array filled with ones:\n {array_ones1} ")


Array of 10 ones: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
A 2D array filled with ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] 


#### 4.4. Create an array of 10 fives

In [ ]:
array_fives = np.full(10, 5)
print(f"Array of 10 fives: {array_fives} ")

# another way
array_fives1 = np.ones(10) * 5
print(f"Array of 10 fives in another way: {array_fives1} ")

Array of 10 fives: [5 5 5 5 5 5 5 5 5 5] 
Array of 10 fives in another way: [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.] 


#### 4.5. Create an array of the integers from 10 to 50

In [ ]:
integers = np.arange(10, 51)
print(f"\nArray of integers from 10 to 50: \n {integers}")
print ()

# Create an array of integers from 10 to 50 but only include numbers divisible by 3
divisible = []
for i in range (51):
  if i % 3 == 0:
    divisible.append(i)

print ("The numbers divisible by 3 between \" 0 and 50 \" are: \n", np.array(divisible))


Array of integers from 10 to 50: 
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]

The numbers divisible by 3 between " 0 and 50 " are: 
 [ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48]


#### 4.6. Create an array of all the even integers from 10 to 50

In [ ]:
even_integers = np.arange(10, 51, 2)
print(f"\nArray of integers from 10 to 50: \n{even_integers}")


Array of integers from 10 to 50: 
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


#### 4.7. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
matr = np.arange(0, 9).reshape(3, 3)
print("3x3 Matrix with values ranging from 0 to 8:")
print (matr)
print ()

# Create a 4x4 matrix with values ranging from 0 to 15 and then reshape it into a 2x8 matrix.
array_1d = np.arange(16)
matrix_4x4 = array_1d.reshape(4, 4)
matrix_2x8 = matrix_4x4.reshape(2, 8)

print("Original 4x4 Matrix:")
print(matrix_4x4)
print ()
print("Reshaped 2x8 Matrix:")
print(matrix_2x8)

3x3 Matrix with values ranging from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Original 4x4 Matrix:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Reshaped 2x8 Matrix:
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


#### 4.8. Create a 3x3 identity matrix

In [ ]:
identity_matrix = np.eye (3)
print("A 3x3 Identity Matrix:")
print(identity_matrix)
print ()

# Create a 4x4 matrix with random integers between 1 and 10
matrix2 = np.random.randint(1, 11, size=(4, 4))
print ("A 4x4 matrix with random integers between 1 and 10:", "\n", matrix2)

A 3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

A 4x4 matrix with random integers between 1 and 10: 
 [[ 2  9  4 10]
 [ 6  4  7  7]
 [ 8 10  9 10]
 [ 3  6  2  1]]


#### 4.9. Use NumPy to generate a random number between 0 and 1

In [3]:
random_number = np.random.rand(1)
print("Random number between 0 and 1:")
print(random_number)
print ()

# generate a 3x3 array of random numbers
array3x3 = np.random.randint (50, 200, size=(3, 3))
print ("A 3x3 array of random numbers:","\n",array3x3)

Random number between 0 and 1:
[0.18126465]

A 3x3 array of random numbers: 
 [[158  84 177]
 [192 162  73]
 [ 56 102 195]]


#### 4.10. Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [ ]:
random_numbers_normal_distribution = np.random.randn(25)
print("Array of 25 random numbers sampled from a standard normal distribution:")
print(random_numbers_normal_distribution)

Array of 25 random numbers sampled from a standard normal distribution:
[-0.14600221  0.32414628 -1.61502726  0.02908865  0.1827234   1.19459461
  0.3427919   0.6636602   0.00233578  1.51249029 -1.19353848 -1.23223436
  0.26575083 -0.32554154 -1.4840739   0.67995468  0.78933365 -1.52656683
 -1.51747544  0.67577853  0.16544258 -0.66733694  0.77519193  0.08549024
  2.0750064 ]


#### 4.11. Create an array of 20 linearly spaced points between 0 and 1:

In [ ]:
linear_spaced_points = np.linspace(0, 1, 20)
print("Array of 20 linearly spaced points between 0 and 1:")
print(linear_spaced_points)

Array of 20 linearly spaced points between 0 and 1:
[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


## 4.12. Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## 4.13.
### WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
### BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
### BE ABLE TO SEE THE OUTPUT ANY MORE



```
array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])


```



In [ ]:
# Create arrays for each row
row1 = np.arange(12, 16)
row2 = np.arange(17, 21)
row3 = np.arange(22, 26)

# Concatenate the arrays vertically
result_array = np.vstack((row1, row2, row3))

print(result_array)


[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


## 4.14.

#### WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
#### BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
#### BE ABLE TO SEE THE OUTPUT ANY MORE



```
20
```



In [ ]:
x = np.array (20)
print (x)

20


## 4.15.

#### WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
#### BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
### BE ABLE TO SEE THE OUTPUT ANY MORE



```
array([[ 2],
       [ 7],
       [12]])

```



In [ ]:
y = np.arange(2, 13, 5)
y.reshape((3, 1))

array([[ 2],
       [ 7],
       [12]])

## 4.16.

#### WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
#### BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
#### BE ABLE TO SEE THE OUTPUT ANY MORE


```
array([21, 22, 23, 24, 25])

```



In [ ]:
z = np.arange(21, 26)
z

array([21, 22, 23, 24, 25])

## 4.17.

#### WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
#### BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
#### BE ABLE TO SEE THE OUTPUT ANY MORE




```
array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

```

In [ ]:
q = np.arange(16, 26).reshape(2, 5)
q

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

## 4.18.
#### Get the sum of all the values in mat

In [ ]:
# Calculate the summation

mat.sum()

325

## 4.19.

#### Get the standard deviation of the values in mat

In [ ]:
# Calculate the standard deviation along axis 0 (columns)
std_dev_axis0 = np.std(mat, axis=0)

# Calculate the standard deviation along axis 1 (rows)
std_dev_axis1 = np.std(mat, axis=1)

print("Standard deviation along axis 0 (columns):","\n", std_dev_axis0)
print("Standard deviation along axis 1 (rows):","\n", std_dev_axis1)

Standard deviation along axis 0 (columns): 
 [7.07106781 7.07106781 7.07106781 7.07106781 7.07106781]
Standard deviation along axis 1 (rows): 
 [1.41421356 1.41421356 1.41421356 1.41421356 1.41421356]


## 4.20.

#### Get the sum of all the columns in mat

In [ ]:
# Calculate the sum of all the columns
column_sums = np.sum(mat, axis=0)

print("Sum of all the columns:")
print(column_sums)

Sum of all the columns:
[55 60 65 70 75]


# Great Job!